# Generated by Django 2.2.2 on 2019-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='SOME STRING', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
