# Generated by Django 2.2.2 on 2019-07-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190708_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='pri',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
