# Generated by Django 2.2.2 on 2019-07-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_destination_pri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='pri',
            new_name='price',
        ),
    ]
